### ISSUE TITLE
Initiate a package review request

### ISSUE THREAD

**Issue by d-sel** [UBC-MDS/instaeda_R#33]
Use template.
https://github.com/ropensci/software-review/issues/new?assignees=&labels=&template=A-submit-software-for-review.md

**Comment by roycezhou** [comment]
request under [request](https://github.com/UBC-MDS/software-review-2021/issues/17)

**Comment by d-sel** [comment]
Please correct Submitting Author section: Selma Duric (@d-sel )

Rest of it looks great!

**Comment by roycezhou** [comment]
Updated!
