### ISSUE TITLE
Improvements to code coverage

### ISSUE THREAD

**Issue by d-sel** [UBC-MDS/instaeda_R#35]
See if there is an opportunity to improve code coverage:

@@           Coverage Diff           @@
##             main      #34   +/-   ##
=======================================
  Coverage        ?   89.94%           
=======================================
  Files           ?        1           
  Lines           ?      169           
  Branches        ?        0           
=======================================
  Hits            ?      152           
  Misses          ?       17           
  Partials        ?        0

**Comment by zmerpez** [comment]
We got nearly 94.6% with last PR.
